### ISSUE TITLE
Autocompletion breaks when filling arguments

### ISSUE THREAD

**Issue by valtzu** [valtzu/codemirror-lang-el#4]
**Version:** 0.5.0

```
is_granted('', )
```

Results in 

```
view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7 CodeMirror plugin crashed: DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at be.fromClass.eventObservers.scroll.createTooltip (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:155937)
    at Mo.createTooltipView (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:154003)
    at Mo.update (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:152679)
    at be.fromClass.eventObservers.scroll.update (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:155122)
    at ye.update (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:33635)
    at gs.updatePlugins (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:123387)
    at gs.update (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:121637)
    at gs.dispatchTransactions (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:119583)
    at gs.dispatch (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:120364)
    at cs (http://localhost:8050/assets/vendor/@codemirror/view/view.index-701f4b05dd57464ba0ecf88b8c48bcdd.js:7:108670)

**Comment by valtzu** [comment]
Tooltips were refactored a bit on `@codemirror/view` `6.24.0` – `6.23.1` is the last working version :disappointed_relieved: 

Constraining the version for now..
